eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
server:
  port: 8897
spring:
  application:
    name: b2b-manage
feign:
  hystrix:
    enabled: true
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
