server:
  port: 8750
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/b2bgoods?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100
  application:
    name: b2b-goods-provider
  mvc:
    hiddenmethod:
      filter:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:/mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

